I'm sorry, but an uncaught exception occurred.

While parsing C:\Users\Hyungju Moon\Desktop\In-Distorted-Space/game/script.rpy.
ScriptError: Name u'introduction' is defined twice, at lib/windows-i686/billscript.rpyc:1 and lib/windows-i686/script.rpyc:42.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Hyungju Moon\Desktop\renpy-6.99.10-sdk\renpy\bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "C:\Users\Hyungju Moon\Desktop\renpy-6.99.10-sdk\renpy\main.py", line 354, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\Users\Hyungju Moon\Desktop\renpy-6.99.10-sdk\renpy\script.py", line 259, in load_script
    self.load_appropriate_file(".rpyc", ".rpy", dir, fn, initcode)
  File "C:\Users\Hyungju Moon\Desktop\renpy-6.99.10-sdk\renpy\script.py", line 738, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=fn + source)
  File "C:\Users\Hyungju Moon\Desktop\renpy-6.99.10-sdk\renpy\script.py", line 414, in finish_load
    bad_node.filename, bad_node.linenumber))
ScriptError: Name u'introduction' is defined twice, at lib/windows-i686/billscript.rpyc:1 and lib/windows-i686/script.rpyc:42.

Windows-8-6.2.9200
Ren'Py 6.99.10.1227
 
